import 'package:custom_lint_builder/custom_lint_builder.dart';
import 'package:nilts/src/lints/unnecessary_rebuilds_from_media_query.dart';

/// custom_lint integrates the nilts's plugin from this method on
/// `custom_lint_client.dart` which is generated by custom_lint CLI.
PluginBase createPlugin() => _NiltsLint();

/// A class for defining all lint rules and assists managed by nilts.
class _NiltsLint extends PluginBase {
  @override
  List<LintRule> getLintRules(CustomLintConfigs configs) => [
        const UnnecessaryRebuildsFromMediaQuery(),
      ];
}
